### ISSUE TITLE
Integrate "principles" with T4D Playbook?

### ISSUE THREAD

**Issue by gabrielkrieshok** [Courtney-Clark/osm-toolkit#1]
I'm thinking that the Principles section could either link to or use similar language to (maybe not all of it) the [T4D Playbook](http://peacecorps.github.io/t4d-playbook/)?

**Comment by Courtney-Clark** [comment]
Yes, I really like that idea! I’ll copy some of the plays into the principles. Thanks for all the commits, too.

**Comment by Courtney-Clark** [comment]
Resolved: have pulled from plays to update principles
